### ISSUE TITLE
Two issues with real device deployment

### ISSUE THREAD

**Issue by laotanlaoban** [YanjieZe/3D-Diffusion-Policy#101]
Hello, I am trying to use the data I collected to achieve DP3 real machine deployment, and I have encountered two problems:

The depth images I collected using the D435 at a resolution of 1280720 are processed very slowly when sampling the point cloud with FPS. I noticed that in your real machine case for pouring, the image resolution used for training is only 84*84. Is the image resolution collected by obs also the same during the eval process? If I lower the resolution of the D435, will it affect the quality of the generated point cloud ?(I noticed you mentioned that the quality of the 435 is not good, but I haven't purchased the 515 yet)

If I enable img images as obs during the real machine training and eval process, will it help improve the success rate of my current eval process? Currently, the success rate of executing my tasks during eval is very low.

**Comment by YanjieZe** [comment]
Hi, thank you for your interest.
As you mention, farthest point sampling is very slow if directly applied to a large image.
This problem is address in [our later paper](https://humanoid-manipulation.github.io/)
Please check the realsense utils here: https://github.com/YanjieZe/Improved-3D-Diffusion-Policy/blob/main/Improved-3D-Diffusion-Policy/diffusion_policy_3d/common/multi_realsense.py
