### ISSUE TITLE
About dexart benchmark

### ISSUE THREAD

**Issue by seagul1** [YanjieZe/3D-Diffusion-Policy#21]
Hello!
when I train DP3 under dexart bucket, the result shows the success rate on train env is lower than test env, Is that normal? And i want to know which success rate you use in your paper?

**Comment by YanjieZe** [comment]
Yes, it is normal. The `test env` there means using some test objects not seen in the training environment. This environment is originally provided by the dexart paper. In our paper, we only study the training environment, since in the test environment the results are just generally lower and do not show other new information.

We might consider removing this part in the code in future, if it leads to confusion.

**Comment by seagul1** [comment]
Thanks for your prompt reply！
