### ISSUE TITLE
Questions about visualisation

### ISSUE THREAD

**Issue by Ju6276** [YanjieZe/3D-Diffusion-Policy#75]
Thanks for all the work you guys are doing! I am trying to deploy dp3 on a real machine.
I see visual animations of real tasks on the homepage. Is this a trained strategy or a collected demo? If it is a demo, also how can I generate the animation from a .zarr file in Visualizer?
Also, how can I deploy and verify in a simulation environment for a trained policy?

Thank you for your answer.

**Comment by YanjieZe** [comment]
Hi, it is visualized by our provided visualizer (I think I may done slight changes, but it is basically the same code). Basically my visualizer is to visualize a point cloud. So to visualize zarr file, you need to first load it and visualize point clouds one by one.
Our training scripts actually have included the deployment in simulation (otherwise you can not get the success rate hhh.)
